// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nvpewduqhfnnwnvzheez.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52cGV3ZHVxaGZubndudnpoZWV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4MjA4MDQsImV4cCI6MjA1NzM5NjgwNH0._5pCei_AUq00lAkyawyDzS4f-TQbRvfkSHx4e8Lt4ic";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);